services:
  legacy:
    container_name: legacy
    build:
      context: ./legacy # Directory containing the Python Dockerfile
    volumes:
      - ./data:/data
      
volumes:
  data:
  communication:
  db_dashboard-data:
