CREATE TABLE IF NOT EXISTS climate_data_attributes (
    attribute_code VARCHAR(50) PRIMARY KEY,
    description TEXT
);

-- Insert general attribute codes and descriptions
INSERT INTO climate_data_attributes (attribute_code, description) VALUES
('Year', 'The year when the data was recorded'),
('Cloud_cover', 'The amount of cloud cover'),
('Potential_evapotranspiration', 'The potential evapotranspiration (PET)'),
('Precipitation_rate', 'The rate of precipitation'),
('Minimum_2m_temperature', 'The minimum temperature at 2 meters above the ground'),
('Mean_2m_temperature', 'The mean temperature at 2 meters above the ground'),
('Maximum_2m_temperature', 'The maximum temperature at 2 meters above the ground'),
('Vapour_pressure', 'The pressure of water vapor in the atmosphere'),
('Frost_days', 'The number of frost days'),
('Wet_days', 'The number of wet days'),

('Cloud cover', 'The amount of cloud cover'),
('potential evapo-transpiration', 'The potential evapotranspiration (PET)'),
('Precipitation rate', 'The rate of precipitation'),
('Minimum 2m temperature', 'The minimum temperature at 2 meters above the ground'),
('Mean 2m temperature', 'The mean temperature at 2 meters above the ground'),
('Maximum 2m temperature', 'The maximum temperature at 2 meters above the ground'),
('Vapour pressure', 'The pressure of water vapor in the atmosphere'),
('Frost days', 'The number of frost days'),
('Wet days', 'The number of wet days'),

-- Insert seasonal breakdowns of these attributes
('cld_MAM', 'Cloud cover for spring (March, April, May)'),
('cld_JJA', 'Cloud cover for summer (June, July, August)'),
('cld_SON', 'Cloud cover for autumn (September, October, November)'),
('cld_DJF', 'Cloud cover for winter (December, January, February)'),
('pet_MAM', 'Potential evapotranspiration for spring (March, April, May)'),
('pet_JJA', 'Potential evapotranspiration for summer (June, July, August)'),
('pet_SON', 'Potential evapotranspiration for autumn (September, October, November)'),
('pet_DJF', 'Potential evapotranspiration for winter (December, January, February)'),
('pre_MAM', 'Precipitation rate for spring (March, April, May)'),
('pre_JJA', 'Precipitation rate for summer (June, July, August)'),
('pre_SON', 'Precipitation rate for autumn (September, October, November)'),
('pre_DJF', 'Precipitation rate for winter (December, January, February)'),
('tmn_MAM', 'Minimum 2m temperature for spring (March, April, May)'),
('tmn_JJA', 'Minimum 2m temperature for summer (June, July, August)'),
('tmn_SON', 'Minimum 2m temperature for autumn (September, October, November)'),
('tmn_DJF', 'Minimum 2m temperature for winter (December, January, February)'),
('tmp_MAM', 'Mean 2m temperature for spring (March, April, May)'),
('tmp_JJA', 'Mean 2m temperature for summer (June, July, August)'),
('tmp_SON', 'Mean 2m temperature for autumn (September, October, November)'),
('tmp_DJF', 'Mean 2m temperature for winter (December, January, February)'),
('tmx_MAM', 'Maximum 2m temperature for spring (March, April, May)'),
('tmx_JJA', 'Maximum 2m temperature for summer (June, July, August)'),
('tmx_SON', 'Maximum 2m temperature for autumn (September, October, November)'),
('tmx_DJF', 'Maximum 2m temperature for winter (December, January, February)'),
('vap_MAM', 'Vapour pressure for spring (March, April, May)'),
('vap_JJA', 'Vapour pressure for summer (June, July, August)'),
('vap_SON', 'Vapour pressure for autumn (September, October, November)'),
('vap_DJF', 'Vapour pressure for winter (December, January, February)'),
('frs_MAM', 'Frost days for spring (March, April, May)'),
('frs_JJA', 'Frost days for summer (June, July, August)'),
('frs_SON', 'Frost days for autumn (September, October, November)'),
('frs_DJF', 'Frost days for winter (December, January, February)'),
('wet_MAM', 'Wet days for spring (March, April, May)'),
('wet_JJA', 'Wet days for summer (June, July, August)'),
('wet_SON', 'Wet days for autumn (September, October, November)'),
('wet_DJF', 'Wet days for winter (December, January, February)'),
('dtr_MAM', 'Diurnal temperature range for spring (March, April, May)'),
('dtr_JJA', 'Diurnal temperature range for summer (June, July, August)'),
('dtr_SON', 'Diurnal temperature range for autumn (September, October, November)'),
('dtr_DJF', 'Diurnal temperature range for winter (December, January, February)'),
('wind_speed_10m_max', 'Maximum wind speed at 10 meters above the ground');
